# Generated by Django 3.2.8 on 2021-10-11 14:18

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_clientes_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajasOperaciones',
            fields=[
                ('caja_operacion_id', models.AutoField(db_column='caja_operacion_id', primary_key=True, serialize=False)),
                ('fecha', utils.custome_db_types.DateFieldCustome(blank=True, null=True)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_cierre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usuario_perfil_apertura_id', models.IntegerField()),
                ('usuario_perfil_apertura_r_id', models.IntegerField()),
                ('usuario_perfil_cierre_id', models.IntegerField()),
                ('usuario_perfil_cierre_r_id', models.IntegerField()),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('caja_id', models.ForeignKey(db_column='caja_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.cajas')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
            ],
            options={
                'db_table': 'cajas_operaciones',
            },
        ),
        migrations.CreateModel(
            name='CajasOperacionesDetalles',
            fields=[
                ('caja_operacion_detalle_id', models.AutoField(db_column='caja_operacion_detalle_id', primary_key=True, serialize=False)),
                ('cantidad_apertura', models.IntegerField()),
                ('cantidad_cierre', models.IntegerField()),
                ('caja_operacion_id', models.ForeignKey(db_column='caja_operacion_id', on_delete=django.db.models.deletion.PROTECT, to='cajas.cajasoperaciones')),
                ('moneda_id', models.ForeignKey(db_column='moneda_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.monedas')),
            ],
            options={
                'db_table': 'cajas_operaciones_detalles',
            },
        ),
        migrations.CreateModel(
            name='CajasMovimientos',
            fields=[
                ('caja_movimiento_id', models.AutoField(db_column='caja_movimiento_id', primary_key=True, serialize=False)),
                ('fecha', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('concepto', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('caja1_id', models.ForeignKey(db_column='caja1_id', on_delete=django.db.models.deletion.PROTECT, related_name='primera_caja', to='configuraciones.cajas', verbose_name='caja1')),
                ('caja1_user_perfil_id', models.ForeignKey(db_column='caja1_user_perfil_id', on_delete=django.db.models.deletion.PROTECT, related_name='primer_usuario', to='permisos.usersperfiles', verbose_name='usuario1')),
                ('caja2_id', models.ForeignKey(db_column='caja2_id', on_delete=django.db.models.deletion.PROTECT, related_name='segunda_caja', to='configuraciones.cajas', verbose_name='caja2')),
                ('caja2_user_perfil_id', models.ForeignKey(db_column='caja2_user_perfil_id', on_delete=django.db.models.deletion.PROTECT, related_name='segundo_usuario', to='permisos.usersperfiles', verbose_name='usuario2')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('tipo_moneda_id', models.ForeignKey(db_column='tipo_moneda_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.tiposmonedas')),
            ],
            options={
                'db_table': 'cajas_movimientos',
            },
        ),
        migrations.CreateModel(
            name='CajasIngresos',
            fields=[
                ('caja_ingreso_id', models.AutoField(db_column='caja_ingreso_id', primary_key=True, serialize=False)),
                ('venta_id', models.IntegerField(default=0)),
                ('caja_movimiento_id', models.IntegerField(default=0)),
                ('es_garantia', models.IntegerField(default=0)),
                ('fecha', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('concepto', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('caja_id', models.ForeignKey(db_column='caja_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.cajas')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'cajas_ingresos',
            },
        ),
        migrations.CreateModel(
            name='CajasEgresos',
            fields=[
                ('caja_egreso_id', models.AutoField(db_column='caja_egreso_id', primary_key=True, serialize=False)),
                ('venta_id', models.IntegerField(default=0)),
                ('caja_movimiento_id', models.IntegerField(default=0)),
                ('es_garantia', models.IntegerField(default=0)),
                ('fecha', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('concepto', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user_perfil_id_anula', models.IntegerField(null=True)),
                ('motivo_anula', models.CharField(max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('caja_id', models.ForeignKey(db_column='caja_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.cajas')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'cajas_egresos',
            },
        ),
    ]
