# Generated by Django 3.2.8 on 2021-10-16 19:12

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_db_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('venta_id', models.AutoField(db_column='venta_id', primary_key=True, serialize=False)),
                ('apellidos', models.CharField(default='', max_length=150)),
                ('nombres', models.CharField(default='', max_length=150)),
                ('ci_nit', models.CharField(default='', max_length=150)),
                ('telefonos', models.CharField(default='', max_length=150)),
                ('factura_a', models.CharField(default='', max_length=150)),
                ('numero_contrato', models.CharField(default='', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('garantia', models.CharField(default='', max_length=250)),
                ('garantia_bs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('direccion_evento', models.TextField(default='')),
                ('observacion', models.TextField(default='')),
                ('fecha_entrega', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('fecha_devolucion', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('fecha_evento', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('dias', models.IntegerField(default=0)),
                ('fecha_preventa', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_preventa', models.IntegerField(default=0)),
                ('fecha_venta', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_venta', models.IntegerField(default=0)),
                ('fecha_salida', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_salida', models.IntegerField(default=0)),
                ('fecha_vuelta', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_vuelta', models.IntegerField(default=0)),
                ('fecha_finaliza', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_finaliza', models.IntegerField(default=0)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('almacen_id', models.ForeignKey(db_column='almacen_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.almacenes')),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='VentasAumentos',
            fields=[
                ('venta_aumento_id', models.AutoField(db_column='venta_aumento_id', primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('garantia', models.CharField(default='', max_length=250)),
                ('garantia_bs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.TextField(default='')),
                ('fecha_salida', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_salida', models.IntegerField(default=0)),
                ('fecha_vuelta', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_vuelta', models.IntegerField(default=0)),
                ('fecha_finaliza', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('user_perfil_id_finaliza', models.IntegerField(default=0)),
                ('user_perfil_id_anula', models.IntegerField(blank=True, null=True)),
                ('motivo_anula', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_db_types.DateTimeFieldCustome(blank=True, null=True)),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.status')),
                ('user_perfil_id', models.ForeignKey(db_column='user_perfil_id', on_delete=django.db.models.deletion.PROTECT, to='permisos.usersperfiles')),
                ('venta_id', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.ventas')),
            ],
            options={
                'db_table': 'ventas_aumentos',
            },
        ),
        migrations.CreateModel(
            name='VentasDetalles',
            fields=[
                ('venta_detalle_id', models.AutoField(db_column='venta_detalle_id', primary_key=True, serialize=False)),
                ('cantidad_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_vuelta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total_rotura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_refaccion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vuelta_rotura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detalle', models.CharField(default='', max_length=250)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('venta_id', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.ventas')),
            ],
            options={
                'db_table': 'ventas_detalles',
            },
        ),
        migrations.CreateModel(
            name='VentasAumentosDetalles',
            fields=[
                ('venta_aumento_detalle_id', models.AutoField(db_column='venta_aumento_detalle_id', primary_key=True, serialize=False)),
                ('cantidad_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_vuelta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total_rotura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_refaccion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vuelta_rotura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detalle', models.CharField(default='', max_length=250)),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productos')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='configuraciones.puntos')),
                ('venta_aumento_id', models.ForeignKey(db_column='venta_aumento_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.ventasaumentos')),
                ('venta_id', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.PROTECT, to='ventas.ventas')),
            ],
            options={
                'db_table': 'ventas_aumentos_detalles',
            },
        ),
    ]
