# Generated by Django 3.2.8 on 2021-10-10 15:51

from django.db import migrations
from configuraciones.models import Lineas
from permisos.models import UsersPerfiles
from status.models import Status
from productos.models import Productos
import openpyxl
import os
from django.conf import settings
from decimal import Decimal


def load_data(apps, schema_editor):
    user_perfil = UsersPerfiles.objects.get(pk=1)
    activo = Status.objects.get(pk=1)
    inactivo = Status.objects.get(pk=2)

    ruta_xlsx = os.path.join(settings.STATICFILES_DIRS[0], 'lineas_productos.xlsx')
    wb_obj = openpyxl.load_workbook(ruta_xlsx)
    hoja_lineas = wb_obj['lineas']
    i = 0
    lineas_ids = {}
    for row in hoja_lineas.iter_rows(1, max_row=hoja_lineas.max_row):
        # for cell in row:
        if i > 0:
            linea_id = row[0].value
            linea = row[2].value
            codigo = row[3].value
            descripcion = row[4].value
            enabled = 1 if row[5].value == 'si' else 0

            nombre_imagen = linea.replace(' ', '').lower() + '.jpg'
            nombre_imagen_thumb = linea.replace(' ', '').lower() + '_thumb.jpg'

            estado = activo if enabled == 1 else inactivo

            linea_add = Lineas.objects.create(linea=linea, codigo=codigo, linea_principal=1, linea_superior_id=0, descripcion=descripcion,
                                              imagen=nombre_imagen, imagen_thumb=nombre_imagen_thumb, status_id=estado, created_at='now', updated_at='now')
            linea_add.save()
            #print('linea add: ', linea_add)
            lineas_ids[linea_id] = linea_add.linea_id
        i += 1

    # productos
    hoja_productos = wb_obj['productos']
    i = 0
    for row in hoja_productos.iter_rows(1, max_row=hoja_productos.max_row):
        # for cell in row:
        if i > 0:
            linea_id = int(row[1].value)
            para_id = lineas_ids[linea_id]
            para_linea = Lineas.objects.get(pk=para_id)

            producto = row[2].value
            nombre_corto = row[3].value
            codigo = row[4].value
            descripcion = row[5].value
            precio = Decimal(row[6].value)
            precio_factura = Decimal(row[7].value)
            stock_minimo = int(row[9].value)
            costo_rotura = Decimal(row[10].value)

            enabled = 1 if row[11].value == 'si' else 0
            estado = activo if enabled == 1 else inactivo

            producto_add = Productos.objects.create(
                producto=producto, codigo=codigo, descripcion=descripcion, stock_minimo=stock_minimo, precio=precio,
                precio_factura=precio_factura, costo_rotura=costo_rotura,
                linea_id=para_linea, user_perfil_id=user_perfil, status_id=estado,
                created_at='now', updated_at='now')

            producto_add.save()
        i += 1

    # close
    wb_obj.close()


def delete_data(apps, schema_editor):
    productos_del = apps.get_model('productos', 'Productos')
    productos_del.objects.all().delete

    lineas_del = apps.get_model('configuraciones', 'Lineas')
    lineas_del.objects.all().delete


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
    ]
